service: dit
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-west-2
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

plugins:
  - serverless-s3-deploy

custom:
  secrets: ${file(secrets.json)}
  assets:
    targets:
      - bucket: dit-site-bucket-${self:custom.secrets.NODE_ENV}
        files:
          - source: dist
            globs: '**/*'

resources:
  Resources:
    DITSiteS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dit-site-bucket-${self:custom.secrets.NODE_ENV}
        PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html

    DITSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: DITSiteS3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:s3:::"
                    - Ref: DITSiteS3Bucket
                    - "/*"